DROP DATABASE IF EXISTS OJC;
CREATE DATABASE IF NOT EXISTS OJC;
CREATE USER IF NOT EXISTS 'OJC_ADMIN'@'LOCALHOST' IDENTIFIED BY 'ojc$123'; 
GRANT ALL ON OJC.* TO 'OJC_ADMIN'@'LOCALHOST' IDENTIFIED BY 'ojc$123'; 

USE OJC;
--
-- Table structure for table `USER_TYPE'
--
CREATE TABLE IF NOT EXISTS OJC_USER_TYPE(
	USER_TYPE_ID	INT NOT NULL AUTO_INCREMENT,
	TYPE			VARCHAR(15) NOT NULL,
	CONSTRAINT USER_TYPE_ID_PK PRIMARY KEY(USER_TYPE_ID)
);
ALTER TABLE OJC_USER_TYPE AUTO_INCREMENT=11;
INSERT INTO OJC_USER_TYPE (TYPE) VALUES ('JS'),('R'),('ADMIN');
--
-- Table structure for table `OJC_JOB_TYPE'
--
CREATE TABLE IF NOT EXISTS OJC_JOB_TYPE(
	JOB_TYPE_ID		INT NOT NULL AUTO_INCREMENT,
	TYPE			VARCHAR(50) NOT NULL,
	CONSTRAINT JOB_TYPE_ID_PK PRIMARY KEY(JOB_TYPE_ID)
);

ALTER TABLE OJC_JOB_TYPE AUTO_INCREMENT=21;
INSERT INTO OJC_JOB_TYPE (TYPE) VALUES ('FULL-TIME'),('PART-TIME');

--
-- Table structure for table `OJC_JOB_INDUSTRY'
--
CREATE TABLE IF NOT EXISTS OJC_JOB_INDUSTRY(
	JOB_INDUSTRY_ID		INT NOT NULL AUTO_INCREMENT,
	TYPE				VARCHAR(50) NOT NULL,
	CONSTRAINT JOB_INDUSTRY_ID_PK PRIMARY KEY(JOB_INDUSTRY_ID)
);
ALTER TABLE OJC_JOB_INDUSTRY AUTO_INCREMENT=31;
INSERT INTO OJC_JOB_INDUSTRY (TYPE) VALUES ('BANKING'),('HOLISTIC'),('INFORMATION-TECHNOLOGY'),('HOTELS');

--
-- Table structure for table `OJC_JOB_EXPERIENCE'a
--
CREATE TABLE IF NOT EXISTS OJC_JOB_EXPERIENCE(
	JOB_EXPERIENCE_ID	INT NOT NULL AUTO_INCREMENT,
	TYPE				VARCHAR(100) NOT NULL,
	CONSTRAINT JOB_EXPERIENCE_ID_PK PRIMARY KEY(JOB_EXPERIENCE_ID)
);

ALTER TABLE OJC_JOB_EXPERIENCE AUTO_INCREMENT=41;
INSERT INTO OJC_JOB_EXPERIENCE (TYPE) VALUES ('GRADUATE'),('3-TO-5-YEARS'),('5-AND-ABOVE');

--
-- Table structure for table `OJC_USER'
--
CREATE TABLE IF NOT EXISTS OJC_USER(
	USER_ID			INT NOT NULL AUTO_INCREMENT,
	FIRST_NAME		VARCHAR(50) NOT NULL,
	LAST_NAME  	    VARCHAR(50) NOT NULL,
	USER_NAME		VARCHAR(50) NOT NULL UNIQUE,
	PASSWORD		VARCHAR(255) NOT NULL,
	USER_TYPE_ID 	INT NOT NULL,	
    UPDATED_DATE 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT USER_ID_PK PRIMARY KEY(USER_ID),
	CONSTRAINT USER_TYPE_ID_USER_FK FOREIGN KEY(USER_TYPE_ID) REFERENCES OJC_USER_TYPE(USER_TYPE_ID)
);

ALTER TABLE OJC_USER AUTO_INCREMENT=101;
INSERT INTO OJC_USER (FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,USER_TYPE_ID)VALUES ('user1','user1','user1@ojc.com',md5('password$123'),11);
INSERT INTO OJC_USER (FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,USER_TYPE_ID)VALUES ('user2','user2','user2@ojc.com',md5('password$123'),11);
INSERT INTO OJC_USER (FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,USER_TYPE_ID)VALUES ('user3','user3','user3@ojc.com',md5('password$123'),11);
INSERT INTO OJC_USER (FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,USER_TYPE_ID)VALUES ('user4','user4','user4@ojc.com',md5('password$123'),11);
INSERT INTO OJC_USER (FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,USER_TYPE_ID)VALUES ('user5','user5','user5@ojc.com',md5('password$123'),12);
INSERT INTO OJC_USER (FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,USER_TYPE_ID)VALUES ('user6','user6','user6@ojc.com',md5('password$123'),12);
INSERT INTO OJC_USER (FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,USER_TYPE_ID)VALUES ('user7','user7','user7@ojc.com',md5('password$123'),12);
INSERT INTO OJC_USER (FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,USER_TYPE_ID)VALUES ('user8','user8','user8@ojc.com',md5('password$123'),12);
INSERT INTO OJC_USER (FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,USER_TYPE_ID)VALUES ('user9','user9','user9@ojc.com',md5('password$123'),11);
INSERT INTO OJC_USER (FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,USER_TYPE_ID)VALUES ('user10','user10','user10@ojc.com',md5('password$123'),12);
INSERT INTO OJC_USER (FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,USER_TYPE_ID)VALUES ('ADMIN','DEEPIKA','admin@ojc.com',md5('password$123'),13);
INSERT INTO OJC_USER (FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,USER_TYPE_ID)VALUES ('user11','user11','user11@ojc.com',md5('password$123'),11);
INSERT INTO OJC_USER (FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,USER_TYPE_ID)VALUES ('user12','user12','user12@ojc.com',md5('password$123'),11);
INSERT INTO OJC_USER (FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,USER_TYPE_ID)VALUES ('user13','user13','user13@ojc.com',md5('password$123'),11);
INSERT INTO OJC_USER (FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,USER_TYPE_ID)VALUES ('user14','user14','user14@ojc.com',md5('password$123'),11);
--
-- Table structure for table `OJC_JS_PROFILE'
--
CREATE TABLE IF NOT EXISTS OJC_JS_PROFILE(
	JS_PROFILE_ID	INT NOT NULL AUTO_INCREMENT,
	USER_ID			INT NOT NULL,
	JOB_TITLE	 	VARCHAR(255) NOT NULL,
	JOB_INDUSTRY	INT NOT NULL,
	JOB_LOCATION	VARCHAR(255) NOT NULL,
	JOB_TYPE		INT NOT NULL,
	JOB_SKILLS		VARCHAR(255) NOT NULL, 
	JOB_EXPERIENCE	INT NOT NULL,
    UPDATED_DATE 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT JS_PROFILE_ID_PK PRIMARY KEY(JS_PROFILE_ID),
	CONSTRAINT USER_ID_JS_PROFILE_FK FOREIGN KEY(USER_ID) REFERENCES OJC_USER(USER_ID),
	CONSTRAINT JOB_INDUSTRY_JS_PROFILE_FK FOREIGN KEY(JOB_INDUSTRY) REFERENCES OJC_JOB_INDUSTRY(JOB_INDUSTRY_ID),
	CONSTRAINT JOB_TYPE_JS_PROFILE_FK FOREIGN KEY(JOB_TYPE) REFERENCES OJC_JOB_TYPE(JOB_TYPE_ID),
	CONSTRAINT JOB_EXPERIENCE_JS_PROFILE_FK FOREIGN KEY(JOB_EXPERIENCE) REFERENCES OJC_JOB_EXPERIENCE(JOB_EXPERIENCE_ID)
);

ALTER TABLE OJC_JS_PROFILE AUTO_INCREMENT=201;
INSERT INTO OJC_JS_PROFILE (USER_ID,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (101,'Accountant','31','MK107FP','21','CFA,CIC,Mathematical and Analytical Ability,Confidence with financial data','41');
INSERT INTO OJC_JS_PROFILE (USER_ID,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (102,'WEB DEVELOPER','33','E16AN','22','JAVASCRIPT,PHP,HTML','43');
INSERT INTO OJC_JS_PROFILE (USER_ID,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (103,'YOGA TRAINER','32','NE11EN','22','Yoga Foundation Certification,Pranayama,Cleansing Techniques','42');
INSERT INTO OJC_JS_PROFILE (USER_ID,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (104,'HOTEL RECEPTIONIST','34','FY11AN','21','Excellent Verbal Communication Skills, Administration Skills','42');
INSERT INTO OJC_JS_PROFILE (USER_ID,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (115,'FINANCE MANAGER','31','CH1 1AA','21','Excellent communication skills, Mathematical and Analytical Ability,Confidence with financial data','41');
INSERT INTO OJC_JS_PROFILE (USER_ID,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (116,'PHP DEVELOPER','33','TR7 2AG','22','PHP,Lavarel','43');
INSERT INTO OJC_JS_PROFILE (USER_ID,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (117,'Private Yoga Instructor','32','L1 1EB','22','Yoga Foundation Certification,Pranayama,Cleansing Techniques','42');
INSERT INTO OJC_JS_PROFILE (USER_ID,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (118,'Bar And Waiting Apprentice','34','HR1 1AG','21','Excellent Verbal Communication Skills, Administration Skills','42');
--
-- Table structure for table `OJC_JOB'
--
CREATE TABLE IF NOT EXISTS OJC_JOB(
	JOB_ID			INT NOT NULL AUTO_INCREMENT,
	USER_ID			INT NOT NULL,
	ORG_NAME		VARCHAR(255) NOT NULL,
	ORG_LOCATION	VARCHAR(255) NOT NULL,
	JOB_TITLE	 	VARCHAR(255) NOT NULL,
	JOB_INDUSTRY	INT NOT NULL,
	JOB_LOCATION	VARCHAR(255) NOT NULL,
	JOB_TYPE		INT NOT NULL,
	JOB_SKILLS		VARCHAR(255) NOT NULL,
	JOB_EXPERIENCE	INT NOT NULL,
    UPDATED_DATE 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT JOB_ID_PK PRIMARY KEY(JOB_ID),
	CONSTRAINT USER_ID_JOB_FK FOREIGN KEY(USER_ID) REFERENCES OJC_USER(USER_ID),
	CONSTRAINT JOB_INDUSTRY_JOB_FK FOREIGN KEY(JOB_INDUSTRY) REFERENCES OJC_JOB_INDUSTRY(JOB_INDUSTRY_ID),
	CONSTRAINT JOB_TYPE_JOB_FK FOREIGN KEY(JOB_TYPE) REFERENCES OJC_JOB_TYPE(JOB_TYPE_ID),
	CONSTRAINT JOB_EXPERIENCE_JOB_FK FOREIGN KEY(JOB_EXPERIENCE) REFERENCES OJC_JOB_EXPERIENCE(JOB_EXPERIENCE_ID)

);

ALTER TABLE OJC_JOB AUTO_INCREMENT=301;
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (105,'Life Groups','MK10 9SU','Accountant','31','MK107FP','21','CFA,CIC,Mathematical and Analytical Ability','41');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (106,'Cube Technologies','E1 7AA','WEB DEVELOPER','33','LA10AF','22','JAVASCRIPT,PHP,HTML','43');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (107,'Cosmic Kids Studio','LA10AF','YOGA TRAINER','32','NE11EN','22','Yoga Foundation Certification,Pranayama,Cleansing Techniques','42');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (108, 'Ramsden Arms Hotel', 'FY13BG', 'HOTEL RECEPTIONIST','32','FY11AN','21','Excellent Verbal Communication Skills, Administration Skills','42');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (105,'Life Groups','MK10 9SU','Branch Manager','31','MK107FP','21','CFA,CIC,Leadership','41');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (106,'Cube Technologies','E1 7AA','Back-end Developer','33','CB7 5GL','22','JAVASCRIPT,PHP','43');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (107,'Cosmic Kids Studio','LA10AF','Quality Assurance Care Officer','32','NE11EN','22','QA Certification','42');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (108, 'Ramsden Arms Hotel', 'FY13BG', 'HOTEL MANAGER','32','FY11AN','21','Managerial Skills','42');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (105,'Life Groups','E1 7AE','FINANCE MANAGER','31','MK10 9SU','21','Excellent communication skills,Excellent people skills,Confidence with financial data','41');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (106,'Cube Technologies','E1 7AA','PHP DEVELOPER','33','E1 7EA','22','PHP,Lavarel','43');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (107,'Cosmic Kids Studio','LA10AF','Private Yoga Instructor','32','MK16QE','22','Vinyasa, Hatha, Ashtanga, Power, pre- or post-natal Yoga or more, but we encourage our Yoga Instructors to work within their speciality','42');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (108, 'Ramsden Arms Hotel', 'FY13BG','Bar And Waiting Apprentice','34','MK107FP','21','enthusiastic, passionate','42');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (105,'Life Groups','E1 7AE','FINANCE MANAGER','31','E1 7AD','21','Excellent communication skills,Excellent people skills,Confidence with financial data','41');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (106,'Cube Technologies','E1 7AA','PHP DEVELOPER','33','NR10 5AJ','22','PHP,Lavarel','43');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (107,'Cosmic Kids Studio','LA10AF','Private Yoga Instructor','32','CB7 5GL','22','Vinyasa, Hatha, Ashtanga, Power, pre- or post-natal Yoga or more, but we encourage our Yoga Instructors to work within their speciality','42');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (108, 'Ramsden Arms Hotel', 'FY63BG','Bar And Waiting Apprentice','34','MK107FP','21','enthusiastic, passionate','42');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (105,'Life Groups','E1 7AE','FINANCE MANAGER','31','EX16 8AA','21','Excellent communication skills,Excellent people skills,Confidence with financial data','41');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (106,'Cube Technologies','E1 7AA','PHP DEVELOPER','33','NR10 5AJ','22','PHP,Lavarel','43');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (107,'Cosmic Kids Studio','LA10AF','Private Yoga Instructor','32','HP10 0AA','22','Vinyasa, Hatha, Ashtanga, Power, pre- or post-natal Yoga or more, but we encourage our Yoga Instructors to work within their speciality','42');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (108, 'Ramsden Arms Hotel', 'FY63BG','Bar And Waiting Apprentice','34','OX3','21','enthusiastic, passionate','42');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (105,'Life Groups','E1 7AE','FINANCE MANAGER','31','LU1 3TG','21','Excellent communication skills,Excellent people skills,Confidence with financial data','41');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (106,'Cube Technologies','E1 7AA','PHP DEVELOPER','33','GU15 4DU','22','PHP,Lavarel','43');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (107,'Cosmic Kids Studio','LA10AF','Private Yoga Instructor','32','HA1 3EX','22','Vinyasa, Hatha, Ashtanga, Power, pre- or post-natal Yoga or more, but we encourage our Yoga Instructors to work within their speciality','42');
INSERT INTO OJC_JOB (USER_ID,ORG_NAME,ORG_LOCATION,JOB_TITLE,JOB_INDUSTRY,JOB_LOCATION,JOB_TYPE,JOB_SKILLS,JOB_EXPERIENCE)VALUES (108, 'Ramsden Arms Hotel', 'CB1 0SN','Bar And Waiting Apprentice','34','OX3','21','enthusiastic, passionate','42');
--
-- Table structure for table `OJC_OFFER'
--
CREATE TABLE IF NOT EXISTS OJC_OFFER(
	OFFER_ID		INT NOT NULL AUTO_INCREMENT,
	USER_ID		    INT NOT NULL,
	JOB_ID			INT NOT NULL,
	SUBJECT			VARCHAR(255) NOT NULL,
	MESSAGE			VARCHAR(2000) NOT NULL,
    UPDATED_DATE 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT OFFER_ID_PK PRIMARY KEY(OFFER_ID),
	CONSTRAINT USER_ID_OFFER_FK FOREIGN KEY(USER_ID) REFERENCES OJC_USER(USER_ID),
	CONSTRAINT JOB_ID_OFFER_FK FOREIGN KEY(JOB_ID) REFERENCES OJC_JOB(JOB_ID)
);

ALTER TABLE OJC_OFFER AUTO_INCREMENT=401;

--
-- Table structure for table `OJC_CONTACT'
--
CREATE TABLE IF NOT EXISTS OJC_CONTACT(
	CONTACT_ID		INT NOT NULL AUTO_INCREMENT,
	FULL_NAME		VARCHAR(255) NOT NULL,
	EMAIL_ADDRESS   VARCHAR(255) NOT NULL,
	EMAIL_SUBJECT	VARCHAR(255) NOT NULL,
    EMAIL_MESSAGE 	VARCHAR(255) NOT NULL,
    UPDATED_DATE 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT CONTACT_ID_PK PRIMARY KEY(CONTACT_ID)
);

ALTER TABLE OJC_CONTACT AUTO_INCREMENT=501;
INSERT INTO OJC_CONTACT (FULL_NAME,EMAIL_ADDRESS,EMAIL_SUBJECT,EMAIL_MESSAGE)VALUES ('Deepika','deepikasandp@gmail.com','Hello There','How to regiter with the site');
INSERT INTO OJC_CONTACT (FULL_NAME,EMAIL_ADDRESS,EMAIL_SUBJECT,EMAIL_MESSAGE)VALUES ('Sandeep','deepikasandp@gmail.com','Hello There','How to advertise with the site');
INSERT INTO OJC_CONTACT (FULL_NAME,EMAIL_ADDRESS,EMAIL_SUBJECT,EMAIL_MESSAGE)VALUES ('user4','deepikasandp@gmail.com','Hello There','How to login with the site');